name: The Kingdom School
favicon: null
layout_spectrum: 0.0172917228192091
typography_spectrum: 0.7263496618252248
title: Amazing Kingdom Institute
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#418494'
    - '#000205'
    - '#bb475f'
    - '#9db1b2'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.3711647263262421
  rhythmicContrast: 0.029399008257314563
purpose: []
